language: ruby

rvm:
- 2.3.3

services:
  - postgresql

before_script:
  - cd backend
  - cp config/database.travis.yml config/database.yml
  - bundle install
  - bundle exec rake db:setup

script: bundle exec rspec
